import { RegexRule } from "./types";

interface RawRule {
  name: string;
  regex: string;
  severity: number;
  category: string;
}

const coreRules: RawRule[] = [
  { name: "Tokenized PII Placeholder", regex: "\\[PII_\\d{3,}\\]", severity: 0.88, category: "pii" },
  { name: "Tokenized Credential Placeholder", regex: "\\[CREDENTIAL_\\d{3,}\\]", severity: 0.95, category: "credentials" },
  { name: "Tokenized Secret Placeholder", regex: "\\[SECRET_\\d{3,}\\]", severity: 0.95, category: "credentials" },
  { name: "Tokenized Internal Placeholder", regex: "\\[INTERNAL_\\d{3,}\\]", severity: 0.8, category: "internal" },
  { name: "AWS Access Key ID", regex: "\\bAKIA[0-9A-Z]{16}\\b", severity: 0.98, category: "cloud" },
  { name: "AWS Secret Access Key Assignment", regex: "(?i)aws(.{0,20})?(secret|access).{0,10}[=:]\\s*['\"][A-Za-z0-9/+=]{40}['\"]", severity: 0.98, category: "cloud" },
  { name: "OpenAI API Key", regex: "\\bsk-[A-Za-z0-9]{20,}\\b", severity: 0.98, category: "llm" },
  { name: "OpenAI Style Test Key", regex: "\\bsk-(live|test)-[A-Za-z0-9._-]{6,}\\b", severity: 0.9, category: "llm" },
  { name: "Anthropic API Key", regex: "\\bsk-ant-[A-Za-z0-9_-]{20,}\\b", severity: 0.98, category: "llm" },
  { name: "Google API Key", regex: "\\bAIza[0-9A-Za-z\\-_]{35}\\b", severity: 0.95, category: "cloud" },
  { name: "Google OAuth Token", regex: "\\bya29\\.[0-9A-Za-z\\-_]+\\b", severity: 0.95, category: "cloud" },
  { name: "Azure Storage Key", regex: "(?i)AccountKey\\s*=\\s*[A-Za-z0-9+/=]{80,120}", severity: 0.95, category: "cloud" },
  { name: "Azure SAS Token", regex: "(?i)sv=\\d{4}-\\d{2}-\\d{2}&ss=[a-z]+&srt=[a-z]+&sp=[rwdlacup]+&se=[^&\\s]+&st=[^&\\s]+&spr=https?&sig=[A-Za-z0-9%]+", severity: 0.94, category: "cloud" },
  { name: "GitHub Fine-grained Token", regex: "\\bgithub_pat_[A-Za-z0-9_]{60,255}\\b", severity: 0.98, category: "scm" },
  { name: "GitHub Personal Token", regex: "\\bgh[pousr]_[A-Za-z0-9]{36,255}\\b", severity: 0.98, category: "scm" },
  { name: "GitLab Token", regex: "\\bglpat-[A-Za-z0-9\\-_]{20,}\\b", severity: 0.95, category: "scm" },
  { name: "Slack Bot Token", regex: "\\bxoxb-[0-9]{10,13}-[0-9]{10,13}-[A-Za-z0-9]{24,}\\b", severity: 0.96, category: "saas" },
  { name: "Slack User Token", regex: "\\bxoxp-[0-9]{10,13}-[0-9]{10,13}-[A-Za-z0-9]{24,}\\b", severity: 0.96, category: "saas" },
  { name: "Slack App Token", regex: "\\bxapp-[0-9A-Za-z-]{20,}\\b", severity: 0.94, category: "saas" },
  { name: "Stripe Secret Key", regex: "\\bsk_(live|test)_[0-9A-Za-z]{16,}\\b", severity: 0.96, category: "payments" },
  { name: "Stripe Restricted Key", regex: "\\brk_(live|test)_[0-9A-Za-z]{16,}\\b", severity: 0.92, category: "payments" },
  { name: "Twilio API Key", regex: "\\bSK[0-9a-fA-F]{32}\\b", severity: 0.94, category: "saas" },
  { name: "SendGrid API Key", regex: "\\bSG\\.[A-Za-z0-9_\\-]{20,}\\.[A-Za-z0-9_\\-]{20,}\\b", severity: 0.94, category: "saas" },
  { name: "JWT Token", regex: "\\beyJ[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9_-]{10,}\\b", severity: 0.9, category: "auth" },
  { name: "RSA Private Key", regex: "-----BEGIN RSA PRIVATE KEY-----", severity: 1.0, category: "keys" },
  { name: "EC Private Key", regex: "-----BEGIN EC PRIVATE KEY-----", severity: 1.0, category: "keys" },
  { name: "DSA Private Key", regex: "-----BEGIN DSA PRIVATE KEY-----", severity: 1.0, category: "keys" },
  { name: "OpenSSH Private Key", regex: "-----BEGIN OPENSSH PRIVATE KEY-----", severity: 1.0, category: "keys" },
  { name: "Generic Private Key", regex: "-----BEGIN PRIVATE KEY-----", severity: 1.0, category: "keys" },
  { name: "PEM Block", regex: "-----BEGIN [A-Z ]+-----", severity: 0.9, category: "keys" },
  { name: "PKCS8 Header", regex: "-----BEGIN ENCRYPTED PRIVATE KEY-----", severity: 1.0, category: "keys" },
  { name: "Basic Auth Header", regex: "(?i)Authorization:\\s*Basic\\s+[A-Za-z0-9+/=]{12,}", severity: 0.86, category: "auth" },
  { name: "Bearer Token Header", regex: "(?i)Authorization:\\s*Bearer\\s+[A-Za-z0-9._\\-]{20,}", severity: 0.9, category: "auth" },
  { name: "Authorization Header Generic", regex: "(?i)\\bAuthorization\\b\\s*:\\s*(?:Basic|Bearer|Digest|Token|ApiKey|OAuth)\\s+[^\\s'\\\"]{8,}", severity: 0.9, category: "auth" },
  { name: "OAuth Access Token", regex: "(?i)access[_-]?token\\s*[=:]\\s*['\"][A-Za-z0-9._\\-]{16,}['\"]", severity: 0.88, category: "auth" },
  { name: "OAuth Refresh Token", regex: "(?i)refresh[_-]?token\\s*[=:]\\s*['\"][A-Za-z0-9._\\-]{16,}['\"]", severity: 0.88, category: "auth" },
  { name: "API Token Assignment", regex: "(?i)\\b(?:api[_ -]?token|token)\\b\\s*[=:]\\s*['\"]?[A-Za-z0-9._\\-]{16,}['\"]?", severity: 0.85, category: "auth" },
  { name: "Generic API Key Assignment", regex: "(?i)(api[_-]?key|apikey)\\s*[=:]\\s*['\"][A-Za-z0-9_\\-]{12,}['\"]", severity: 0.82, category: "generic" },
  { name: "Generic API Key Label", regex: "(?i)(api[_ -]?key|apikey)\\s*[:=]\\s*[A-Za-z0-9._\\-]{8,}", severity: 0.84, category: "generic" },
  { name: "License Key Assignment", regex: "(?i)\\b(?:license|licence)\\s*(?:key|code)?\\b\\s*[=:]\\s*['\"]?[A-Z0-9]{4,6}(?:-[A-Z0-9]{4,6}){2,5}['\"]?", severity: 0.87, category: "license" },
  { name: "Activation Code Assignment", regex: "(?i)\\bactivation\\s*(?:code|key)\\b\\s*[=:]\\s*['\"]?[A-Z0-9]{6,32}['\"]?", severity: 0.86, category: "license" },
  { name: "Internal Private IP Address", regex: "\\b(?:10(?:\\.\\d{1,3}){3}|172\\.(?:1[6-9]|2\\d|3[0-1])(?:\\.\\d{1,3}){2}|192\\.168(?:\\.\\d{1,3}){2})\\b", severity: 0.78, category: "internal" },
  { name: "Hostname Assignment", regex: "(?i)\\b(?:hostname|host)\\b\\s*[:=]\\s*['\"]?[A-Za-z0-9][A-Za-z0-9._-]{2,253}['\"]?", severity: 0.72, category: "internal" },
  { name: "User ID Assignment", regex: "(?i)\\b(?:user[_ -]?id|userid|uid)\\b\\s*[:=]\\s*['\"]?[A-Za-z0-9._-]{3,64}['\"]?", severity: 0.74, category: "pii" },
  { name: "File Path Assignment", regex: "(?i)\\b(?:file(?:_?path)?|path|directory|dir)\\b\\s*[:=]\\s*['\"]?(?:[A-Za-z]:\\\\[^'\"\\r\\n]+|\\/(?:[^\\/\\s]+\\/)+[^'\"\\s]+)['\"]?", severity: 0.7, category: "internal" },
  { name: "Database Query Statement", regex: "(?i)\\b(?:select|insert|update|delete)\\b\\s+.{0,240}\\b(?:from|into|set|where)\\b", severity: 0.68, category: "database" },
  { name: "Service URL Assignment", regex: "(?i)\\b(?:service[_ -]?url|endpoint|base[_ -]?url|callback[_ -]?url)\\b\\s*[:=]\\s*['\"]?https?:\\/\\/[^\\s'\"]+['\"]?", severity: 0.76, category: "internal" },
  { name: "Case Number Assignment", regex: "(?i)\\b(?:case[_ -]?(?:number|no|id)|ticket[_ -]?(?:number|no|id))\\b\\s*[:=]?\\s*#?[A-Z0-9-]{4,20}\\b", severity: 0.66, category: "internal" },
  { name: "Server Name Assignment", regex: "(?i)\\bserver[_ -]?name\\b\\s*[:=]\\s*['\"]?[A-Za-z0-9][A-Za-z0-9._-]{2,253}['\"]?", severity: 0.74, category: "internal" },
  { name: "Generic Secret Assignment", regex: "(?i)(secret|client_secret)\\s*[=:]\\s*['\"][A-Za-z0-9._\\-+/=]{8,}['\"]", severity: 0.84, category: "generic" },
  { name: "Password Assignment", regex: "(?i)(password|passwd|pwd)\\s*[=:]\\s*['\"][^'\\\"]{8,}['\"]", severity: 0.86, category: "credentials" },
  { name: "Password Label", regex: "(?i)(password|passwd|pwd)\\s*[:=]\\s*[^\\s]{8,}", severity: 0.88, category: "credentials" },
  { name: "Connection String", regex: "(?i)(Server|Host|Data Source)=[^;\\n]+;(Database|Initial Catalog)=[^;\\n]+;(User Id|UID)=[^;\\n]+;(Password|PWD)=[^;\\n]+", severity: 0.9, category: "database" },
  { name: "MongoDB URI with Credentials", regex: "mongodb(\\+srv)?:\\/\\/[^\\s:@]+:[^\\s@]+@[^\\s]+", severity: 0.92, category: "database" },
  { name: "Postgres URI with Credentials", regex: "postgres(ql)?:\\/\\/[^\\s:@]+:[^\\s@]+@[^\\s]+", severity: 0.92, category: "database" },
  { name: "MySQL URI with Credentials", regex: "mysql:\\/\\/[^\\s:@]+:[^\\s@]+@[^\\s]+", severity: 0.92, category: "database" },
  { name: "Redis URI with Password", regex: "redis:\\/:[^@\\s]{6,}@[^\\s]+", severity: 0.9, category: "database" },
  { name: "NPM Auth Token", regex: "(?i)_authToken\\s*=\\s*[A-Za-z0-9-_.]{20,}", severity: 0.9, category: "package" },
  { name: "Docker Auth Config", regex: "(?i)\\\"auth\\\"\\s*:\\s*\\\"[A-Za-z0-9+/=]{20,}\\\"", severity: 0.9, category: "container" },
  { name: "Kubernetes Token", regex: "(?i)token:\\s*[A-Za-z0-9._\\-]{20,}", severity: 0.88, category: "container" },
  { name: "SSH Public Key", regex: "\\bssh-(rsa|ed25519)\\s+[A-Za-z0-9+/=]{80,}", severity: 0.8, category: "keys" },
  { name: "US Social Security Number", regex: "\\b(?!000|666|9\\d\\d)\\d{3}[- ]?(?!00)\\d{2}[- ]?(?!0000)\\d{4}\\b", severity: 0.9, category: "pii" },
  { name: "Email Address", regex: "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b", severity: 0.6, category: "pii" },
  { name: "Credit Card Number", regex: "\\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|6(?:011|5[0-9]{2})[0-9]{12})\\b", severity: 0.9, category: "financial" },
  { name: "Credit Card Number With Separators", regex: "\\b(?:4[0-9]{3}|5[1-5][0-9]{2}|3[47][0-9]{2}|6(?:011|5[0-9]{2}))([ -]?)\\d{4}\\1\\d{4}\\1\\d{4}\\b", severity: 0.9, category: "financial" },
  { name: "IBAN", regex: "\\b[A-Z]{2}[0-9]{2}[A-Z0-9]{11,30}\\b", severity: 0.75, category: "financial" },
  { name: "US Phone Number", regex: "\\b(?:\\+1[-. ]?)?\\(?[2-9][0-9]{2}\\)?[-. ]?[0-9]{3}[-. ]?[0-9]{4}\\b", severity: 0.55, category: "pii" },
  { name: "India Phone Number", regex: "\\b(?:\\+91[- ]?)?[6-9]\\d{9}\\b", severity: 0.62, category: "pii" },
  { name: "India IFSC Code", regex: "\\b[A-Z]{4}0[A-Z0-9]{6}\\b", severity: 0.82, category: "financial" },
  { name: "India Passport Number", regex: "\\b[A-PR-WYa-pr-wy][0-9]{7}\\b", severity: 0.82, category: "pii" },
  { name: "India Driver License", regex: "\\b[A-Z]{2}[- ]?\\d{2}[- ]?\\d{4}[- ]?\\d{6,7}\\b", severity: 0.82, category: "pii" },
  { name: "Labeled Bank Account Number", regex: "(?i)\\b(bank\\s*account|account\\s*number)\\b\\s*[:=]\\s*\\d{9,18}\\b", severity: 0.86, category: "financial" },
  { name: "Bank Account Natural Language", regex: "(?i)\\bbank\\s*account\\b.{0,16}?\\b\\d{9,18}\\b", severity: 0.86, category: "financial" },
  { name: "Token Natural Language Assignment", regex: "(?i)\\b(token|api[_ -]?key|secret)\\b\\s*(is|:|=)\\s*[A-Za-z0-9._\\-]{8,}", severity: 0.88, category: "generic" },
  { name: "Labeled National ID", regex: "(?i)\\b(national\\s*id|aadhaar|aadhar|ssn|tax\\s*id)\\b\\s*[:=]\\s*[A-Za-z0-9-]{8,}\\b", severity: 0.84, category: "pii" },
  { name: "Labeled Sensitive Placeholder", regex: "(?i)\\b(email|phone|mobile|customer|username|address|passport|driver\\s*license|national\\s*id|bank\\s*account|account\\s*number|ifsc|ip\\s*address|device\\s*id|emergency\\s*contact)\\b\\s*[:=]\\s*\\[(PII|CREDENTIAL|SECRET|INTERNAL|CARD|MEDICAL|EXPORT|COMMAND)_\\d{3,}\\]", severity: 0.9, category: "pii" },
  { name: "Firebase Server Key", regex: "AAAA[A-Za-z0-9_-]{7}:[A-Za-z0-9_-]{140}", severity: 0.92, category: "cloud" },
  { name: "Heroku API Key", regex: "(?i)heroku[a-z0-9_\\-]{0,20}[=:]\\s*['\"]?[0-9a-f]{32}['\"]?", severity: 0.9, category: "saas" },
  { name: "PayPal Access Token", regex: "(?i)access_token\\$production\\$[A-Za-z0-9]{16,}\\$[A-Za-z0-9]{16,}", severity: 0.92, category: "payments" }
];

const providerPrefixes = [
  "aws",
  "gcp",
  "azure",
  "openai",
  "anthropic",
  "huggingface",
  "github",
  "gitlab",
  "bitbucket",
  "slack",
  "stripe",
  "paypal",
  "twilio",
  "sendgrid",
  "mailgun",
  "notion",
  "atlassian",
  "jira",
  "confluence",
  "datadog",
  "newrelic",
  "sentry",
  "segment",
  "snowflake",
  "vercel",
  "netlify",
  "render",
  "digitalocean",
  "cloudflare",
  "fastly",
  "rabbitmq",
  "kafka",
  "mongodb",
  "postgres",
  "mysql",
  "redis",
  "elasticsearch",
  "okta",
  "auth0",
  "supabase",
  "firebase",
  "shopify",
  "salesforce",
  "hubspot",
  "airtable",
  "figma",
  "linear",
  "asana",
  "trello",
  "clickup",
  "discord",
  "telegram",
  "whatsapp",
  "dropbox",
  "box",
  "zoom",
  "teams",
  "adobe",
  "oracle",
  "ibm",
  "sap",
  "vmware",
  "kubernetes",
  "docker",
  "helm",
  "vault",
  "consul",
  "nomad",
  "splunk",
  "pagerduty",
  "opsgenie",
  "prometheus",
  "grafana",
  "algolia",
  "pinecone",
  "weaviate",
  "qdrant"
];

const providerDerivedRules: RawRule[] = providerPrefixes.flatMap((prefix) => [
  {
    name: `${prefix.toUpperCase()} Key Assignment`,
    regex: `(?i)${prefix}[_-]?(api[_-]?key|key)\\s*[=:]\\s*['\"][A-Za-z0-9_\\-]{12,}['\"]`,
    severity: 0.78,
    category: "provider"
  },
  {
    name: `${prefix.toUpperCase()} Token Assignment`,
    regex: `(?i)${prefix}[_-]?(token|access[_-]?token)\\s*[=:]\\s*['\"][A-Za-z0-9._\\-]{12,}['\"]`,
    severity: 0.8,
    category: "provider"
  }
]);

const genericRules: RawRule[] = [
  { name: "Client Secret Assignment", regex: "(?i)client[_-]?secret\\s*[=:]\\s*['\"][A-Za-z0-9._\\-+/=]{8,}['\"]", severity: 0.85, category: "generic" },
  { name: "Private Token Assignment", regex: "(?i)private[_-]?token\\s*[=:]\\s*['\"][A-Za-z0-9._\\-]{10,}['\"]", severity: 0.82, category: "generic" },
  { name: "Access Key Assignment", regex: "(?i)access[_-]?key\\s*[=:]\\s*['\"][A-Za-z0-9._\\-]{10,}['\"]", severity: 0.82, category: "generic" },
  { name: "Webhook Secret Assignment", regex: "(?i)webhook[_-]?secret\\s*[=:]\\s*['\"][A-Za-z0-9._\\-]{10,}['\"]", severity: 0.8, category: "generic" },
  { name: "Encryption Key Assignment", regex: "(?i)encryption[_-]?key\\s*[=:]\\s*['\"][A-Za-z0-9+/=]{16,}['\"]", severity: 0.88, category: "generic" },
  { name: "Master Key Assignment", regex: "(?i)master[_-]?key\\s*[=:]\\s*['\"][A-Za-z0-9._\\-]{10,}['\"]", severity: 0.86, category: "generic" },
  { name: "Secret Environment Variable", regex: "(?i)export\\s+[A-Z0-9_]*(SECRET|TOKEN|PASSWORD|API_KEY)[A-Z0-9_]*=", severity: 0.76, category: "env" }
];

const allRawRules = [...coreRules, ...providerDerivedRules, ...genericRules];

export const regexRules: RegexRule[] = allRawRules.map((rule) => ({
  name: rule.name,
  pattern: new RegExp(rule.regex.replace(/\(\?i\)/g, ""), "gi"),
  severity: rule.severity,
  category: rule.category
}));

export const REGEX_RULE_COUNT = regexRules.length;
